services:
  db:
    image: postgres:15
    container_name: xphr
    hostname: xphr
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: xphr
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - ./db-data:/var/lib/postgresql/data
